name: vegedya_firebase
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^3.1.1
  cloud_firestore: ^5.0.2
  flutter_image_slideshow: ^0.1.6
  flutter_launcher_icons: "^0.13.1"
  shimmer: ^3.0.0
  loading_animation_widget: ^1.2.1
  shared_preferences: ^2.2.3
  top_snackbar_flutter: ^3.1.0
  top_snackbar: ^0.0.6
  firebase_auth: ^5.1.3
  flutter_email_validator: ^2.1.24
  http: ^1.2.2
  connectivity_plus: ^6.0.5
  flutter_html: 3.0.0-beta.2
  intl: ^0.19.0
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^17.2.3
  permission_handler: ^11.3.1
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/icon/
    - assets/images/welcome/
    - assets/images/no-image.jpg
    - assets/images/no_image/no-image.jpg
    - assets/images/waiting/waiting.jpg
    - assets/images/no_image/no-image.jpg
    - assets/images/coming_soon/coming-soon.jpg

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/static/Inter-Regular.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/welcome/spalsh-logo.png"
  min_sdk_android: 21